src/Entity/Appartment.php
<?php

namespace App\Entity;

use App\Exception\BusinessLogicException;
use App\Repository\AppartmentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Exception\InvalidArgumentException;


/**
 * @ORM\Entity(repositoryClass=AppartmentRepository::class)
 */
class Appartment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=5, nullable=false)
     */
    private $number;

    /**
     * @ORM\Column(type="smallint")
     */
    private $numberOfRooms;

    /**
     * @ORM\Column(type="string", length=512, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToMany(targetEntity=Facility::class, inversedBy="appartments")
     */
    private $facilities;

    /**
     * @ORM\OneToMany(targetEntity=AppartmentPricing::class, mappedBy="ID_Appartment")
     */
    private $appartmentPricings;

    /**
     * @ORM\ManyToMany(targetEntity=Reservation::class, mappedBy="appartments")
     */
    private $reservations;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Location;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $basePrice;

    public function __construct()
    {
        $this->facilities = new ArrayCollection();
        $this->appartmentPricings = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    /**
     * @param mixed $number
     */
    public function setNumber($number): void
    {
        $this->number = $number;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNumberOfRooms(): ?int
    {
        return $this->numberOfRooms;
    }

    public function setNumberOfRooms(int $numberOfRooms): self
    {
        if($numberOfRooms < 1){
           throw new BusinessLogicException(" is required");
        }

        $this->numberOfRooms = $numberOfRooms;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Facility[]
     */
    public function getFacilities(): Collection
    {
        return $this->facilities;
    }

    /**
     * @param ArrayCollection $facilities
     */
    public function setFacilities(ArrayCollection $facilities): void
    {
        $this->facilities = $facilities;
    }

    public function addFacility(Facility $facility): self
    {
        if (!$this->facilities->contains($facility)) {
            $this->facilities[] = $facility;
        }

        return $this;
    }

    public function removeFacility(Facility $facility): self
    {
        $this->facilities->removeElement($facility);

        return $this;
    }

    /**
     * @return Collection|AppartmentPricing[]
     */
    public function getAppartmentPricings(): Collection
    {
        return $this->appartmentPricings;
    }

    /**
     * @return AppartmentPricing
     */
    public function getCurrentAppartmentPricing(): AppartmentPricing
    {

        $currentPricing = array_filter($this->appartmentPricings->getValues(), function ($v) {
            return $v->getStartDate() <= new \DateTime() && $v->getEndDate() >= new \DateTime();
        });

        if ($currentPricing && count($currentPricing) > 0) {
            return $currentPricing[0];
        }
        return new AppartmentPricing();

    }

    /**
     * @param ArrayCollection $appartmentPricings
     */
    public function setAppartmentPricings(ArrayCollection $appartmentPricings): void
    {
        $this->appartmentPricings = $appartmentPricings;
    }

    public function addAppartmentPricing(AppartmentPricing $appartmentPricing): self
    {
        if (!$this->appartmentPricings->contains($appartmentPricing)) {
            $this->appartmentPricings[] = $appartmentPricing;
            $appartmentPricing->setIDAppartment($this);
        }

        return $this;
    }

    public function removeAppartmentPricing(AppartmentPricing $appartmentPricing): self
    {
        if ($this->appartmentPricings->removeElement($appartmentPricing)) {
            // set the owning side to null (unless already changed)
            if ($appartmentPricing->getIDAppartment() === $this) {
                $appartmentPricing->setIDAppartment(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    /**
     * @param ArrayCollection $reservations
     */
    public function setReservations(ArrayCollection $reservations): void
    {
        $this->reservations = $reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->addAppartment($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            $reservation->removeAppartment($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->number;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(?string $Location): self
    {
        $this->Location = $Location;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBasePrice(): ?string
    {
        return $this->basePrice;
    }

    public function setBasePrice(string $basePrice): self
    {
        $this->basePrice = $basePrice;

        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 */
class Service
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $Price;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(string $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

}

src/Form/AppartmentType.php
<?php

namespace App\Form;

use App\Entity\Appartment;
use App\Entity\Facility;
use App\Repository\FacilityRepository;
use ContainerJZYVsiV\getFacilityRepositoryService;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AppartmentType extends AbstractType
{


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $facilities = $options['facilities'];

        echo $facilities[0]->getName();

        $builder
            ->add('description')
            ->add('numberOfRooms', NumberType::class, [
                "required" => true
            ])
            ->add('number', TextType::class, [
                "required" => true
            ])
            ->add('location')
            ->add('image', FileType::class,)
//            ->add('facilities', FacilityType::class, [
//                'choices' => $facilities,
//                // "name" is a property path, meaning Symfony will look for a public
//                // property or a public method like "getName()" to define the input
//                // string value that will be submitted by the form
//                'choice_value' => 'name',
//                'by_reference' => false,
//                // a callback to return the label for a given choice
//                // if a placeholder is used, its empty value (null) may be passed but
//                // its label is defined by its own "placeholder" option
//                'choice_label' => function(?Facility $facility) {
//                    return $facility ? strtoupper($facility->getName()) : '';
//                },
//                // returns the html attributes for each option input (may be radio/checkbox)
//                'choice_attr' => function(?Facility $facility) {
//                    return $facility ? ['class' => 'facility_'.strtolower($facility->getName())] : [];
//                },
//
//            ])
            ->add('facilities', ChoiceType::class );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Appartment::class,
        ]);

       $resolver->setRequired('facilities');
    }
}

src/Controller/AppartmentController.php
<?php

namespace App\Controller;

use App\Entity\Appartment;
use App\Entity\Facility;
use App\Form\AppartmentType;
use App\Repository\AppartmentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Uid\Uuid;


/**
 * @Route("/appartment")
 */
class AppartmentController extends AbstractController
{
    /**
     * @Route("/", name="appartment_index", methods={"GET"})
     */
    public function index(AppartmentRepository $appartmentRepository): Response
    {
        return $this->render('appartment/index.html.twig', [
            'appartments' => $appartmentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="appartment_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $appartment = new Appartment();
        $facilities = $this->getDoctrine()
            ->getRepository(Facility::class)->findAll();

        $form = $this->createForm(AppartmentType::class, $appartment, [
            'facilities' => $facilities,
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            //file saving stuff
            /**
             * @var UploadedFile $file
             */
            $file = $request->files->get("appartment")["image"];
            if ($file) {
                $filename = Uuid::v4() . '.' . $file->guessClientExtension();

                $file->move($this->getParameter('appartment_pictures_dir'), $filename);
                $appartment->setImage($filename);
            }

            $entityManager->persist($appartment);
            $entityManager->flush();

            return $this->redirectToRoute('appartment_index');
        }

        return $this->render('appartment/new.html.twig', [
            'appartment' => $appartment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="appartment_show", methods={"GET"})
     */
    public function show(Appartment $appartment): Response
    {
        return $this->render('appartment/show.html.twig', [
            'appartment' => $appartment,
        ]);
    }

    /**
     * @Route("/presentation/{id}", name="appartment_presentation", methods={"GET"})
     */
    public function presentation(Appartment $appartment): Response
    {
        return $this->render('appartment/presentation.html.twig', [
            'appartment' => $appartment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="appartment_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Appartment $appartment): Response
    {
        $form = $this->createForm(AppartmentType::class, $appartment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //file saving stuff
            /**
             * @var UploadedFile $file
             */
            $file = $request->files->get("appartment")["image"];
            if ($file) {
                $filename = Uuid::v4() . '.' . $file->guessClientExtension();

                $file->move($this->getParameter('appartment_pictures_dir'), $filename);
                $appartment->setImage($filename);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('appartment_index');
        }

        return $this->render('appartment/edit.html.twig', [
            'appartment' => $appartment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="appartment_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Appartment $appartment): Response
    {
        if ($this->isCsrfTokenValid('delete' . $appartment->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($appartment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('appartment_index');
    }
}

templates/appartment/_delete_form.html.twig
<form method="post" action="{{ path('appartment_delete', {'id': appartment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ appartment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/appartment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Appartment{% endblock %}

{% block body %}
    <h1>Edit Appartment</h1>

    {{ include('appartment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('appartment_index') }}">back to list</a>

    {{ include('appartment/_delete_form.html.twig') }}
{% endblock %}

templates/appartment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Appartment index{% endblock %}

{% block body %}
    <h1>Appartment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>NumberOfRooms</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for appartment in appartments %}
            <tr>
                <td>{{ appartment.id }}</td>
                <td>{{ appartment.description }}</td>
                <td>{{ appartment.numberOfRooms }}</td>
                <td>{{ appartment.image }}</td>
                <td>
                    <a href="{{ path('appartment_show', {'id': appartment.id}) }}">show</a>
                    <a href="{{ path('appartment_edit', {'id': appartment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('appartment_new') }}">Create new</a>
{% endblock %}

templates/appartment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Appartment{% endblock %}

{% block body %}
    <h1>Create new Appartment</h1>

    {{ include('appartment/_form.html.twig') }}

    <a href="{{ path('appartment_index') }}">back to list</a>
{% endblock %}

templates/appartment/presentation.html.twig
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Appartment</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href={{ asset( "assets/img/favicon.png") }} rel="icon">
    <link href={{ asset("assets/img/apple-touch-icon.png") }} rel="apple-touch-icon">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <link href={{ asset("assets/vendor/bootstrap/css/bootstrap.min.css") }} rel="stylesheet">
    <link href={{ asset("assets/vendor/icofont/icofont.min.css") }} rel="stylesheet">
    <link href={{ asset("assets/vendor/boxicons/css/boxicons.min.css") }} rel="stylesheet">
    <link href={{ asset("assets/vendor/remixicon/remixicon.css") }} rel="stylesheet">
    <link href={{ asset("assets/vendor/venobox/venobox.css") }} rel="stylesheet">
    <link href={{ asset("assets/vendor/owl.carousel/assets/owl.carousel.min.css") }} rel="stylesheet">
    <link href={{ asset("assets/vendor/aos/aos.css") }} rel="stylesheet">

    <link href={{ asset("assets/css/style.css") }} rel="stylesheet">

</head>

<body>

<!-- ======= Header ======= -->
{% include 'header.html.twig' %}

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">

            <div class="d-flex justify-content-between align-items-center">
                <h2>{% trans %}
                        Apartment
                    {% endtrans %}
                </h2>
                {# <ol> #}
                {# <li><a href="index.html">Home</a></li> #}
                {# <li>Portfolio Details</li> #}
                {# </ol> #}
            </div>

        </div>
    </section>

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
        <div class="container">

            <div class="portfolio-details-container" data-aos="fade-up" data-aos-delay="100">

                <div class="owl-carousel portfolio-details-carousel">
                    <img src={{ asset("assets/img/appartments/#{appartment.image}") }} class="img-fluid" alt="">
                    {# <img src={{ asset("assets/img/portfolio/portfolio-details-2.jpg") }} class="img-fluid" alt=""> #}
                    {# <img src={{ asset("assets/img/portfolio/portfolio-details-3.jpg") }} class="img-fluid" alt=""> #}
                </div>

                <div class="portfolio-info">
                    <h3>Appartment information</h3>
                    <ul>
                        <li><strong>Number</strong>: {{ appartment.number }}</li>
                        {# <li><strong>Price*</strong>: {{ appartment.currentAppartmentPricing.price }}</li> #}
                        <li><strong>Price*</strong>: {{ appartment.basePrice }}</li>

                    </ul>
                </div>

            </div>

            <div class="portfolio-description">
                <h2>{{ appartment.name }}</h2>
                <p>
                    {{ appartment.description }}
                </p>
            </div>

            <br>
            <div>
                <h3>{% trans %}
                        Facilities
                    {% endtrans %}
                </h3>
                <ul>
                    {% for facility in appartment.facilities %}
                        <li><strong>{{ facility.name }}</strong>: {{ facility.description }}</li>
                    {% endfor %}
                </ul>
            </div>
            <br>

            <button class="bt"
                    onclick={{ "window.location.href='/Hotel-Management/public/#{app.request.locale}/reservation/new';" }}>
                {% trans %}
                    Reserve
                {% endtrans %}
            </button>
        </div>

    </section><!-- End Portfolio Details Section -->

</main><!-- End #main -->

<!-- ======= Footer ======= -->
{% include 'footer.html.twig' %}


<!-- Vendor JS Files -->
<script src={{ asset("assets/vendor/jquery/jquery.min.js") }}></script>
<script src={{ asset("assets/vendor/bootstrap/js/bootstrap.bundle.min.js") }}></script>
<script src={{ asset("assets/vendor/jquery.easing/jquery.easing.min.js") }}></script>
<script src={{ asset("assets/vendor/php-email-form/validate.js") }}></script>
<script src={{ asset("assets/vendor/waypoints/jquery.waypoints.min.js") }}></script>
<script src={{ asset("assets/vendor/counterup/counterup.min.js") }}></script>
<script src={{ asset("assets/vendor/isotope-layout/isotope.pkgd.min.js") }}></script>
<script src={{ asset("assets/vendor/venobox/venobox.min.js") }}></script>
<script src={{ asset("assets/vendor/owl.carousel/owl.carousel.min.js") }}></script>
<script src={{ asset("assets/vendor/aos/aos.js") }}></script>

<script src={{ asset("assets/js/main.js") }}></script>

</body>

</html>

templates/appartment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Appartment{% endblock %}

{% block body %}
    <h1>Appartment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ appartment.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ appartment.description }}</td>
            </tr>
            <tr>
                <th>NumberOfRooms</th>
                <td>{{ appartment.numberOfRooms }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ appartment.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('appartment_index') }}">back to list</a>

    <a href="{{ path('appartment_edit', {'id': appartment.id}) }}">edit</a>

    {{ include('appartment/_delete_form.html.twig') }}
{% endblock %}