src/Entity/Appartment.php
<?php

namespace App\Entity;

use App\Exception\BusinessLogicException;
use App\Repository\AppartmentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Exception\InvalidArgumentException;


/**
 * @ORM\Entity(repositoryClass=AppartmentRepository::class)
 */
class Appartment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=5, nullable=false)
     */
    private $number;

    /**
     * @ORM\Column(type="smallint")
     */
    private $numberOfRooms;

    /**
     * @ORM\Column(type="string", length=512, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToMany(targetEntity=Facility::class, inversedBy="appartments")
     */
    private $facilities;

    /**
     * @ORM\OneToMany(targetEntity=AppartmentPricing::class, mappedBy="ID_Appartment")
     */
    private $appartmentPricings;

    /**
     * @ORM\ManyToMany(targetEntity=Reservation::class, mappedBy="appartments")
     */
    private $reservations;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Location;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $basePrice;

    public function __construct()
    {
        $this->facilities = new ArrayCollection();
        $this->appartmentPricings = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    /**
     * @param mixed $number
     */
    public function setNumber($number): void
    {
        $this->number = $number;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNumberOfRooms(): ?int
    {
        return $this->numberOfRooms;
    }

    public function setNumberOfRooms(int $numberOfRooms): self
    {
        if($numberOfRooms < 1){
           throw new BusinessLogicException(" is required");
        }

        $this->numberOfRooms = $numberOfRooms;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Facility[]
     */
    public function getFacilities(): Collection
    {
        return $this->facilities;
    }

    /**
     * @param ArrayCollection $facilities
     */
    public function setFacilities(ArrayCollection $facilities): void
    {
        $this->facilities = $facilities;
    }

    public function addFacility(Facility $facility): self
    {
        if (!$this->facilities->contains($facility)) {
            $this->facilities[] = $facility;
        }

        return $this;
    }

    public function removeFacility(Facility $facility): self
    {
        $this->facilities->removeElement($facility);

        return $this;
    }

    /**
     * @return Collection|AppartmentPricing[]
     */
    public function getAppartmentPricings(): Collection
    {
        return $this->appartmentPricings;
    }

    /**
     * @return AppartmentPricing
     */
    public function getCurrentAppartmentPricing(): AppartmentPricing
    {

        $currentPricing = array_filter($this->appartmentPricings->getValues(), function ($v) {
            return $v->getStartDate() <= new \DateTime() && $v->getEndDate() >= new \DateTime();
        });

        if ($currentPricing && count($currentPricing) > 0) {
            return $currentPricing[0];
        }
        return new AppartmentPricing();

    }

    /**
     * @param ArrayCollection $appartmentPricings
     */
    public function setAppartmentPricings(ArrayCollection $appartmentPricings): void
    {
        $this->appartmentPricings = $appartmentPricings;
    }

    public function addAppartmentPricing(AppartmentPricing $appartmentPricing): self
    {
        if (!$this->appartmentPricings->contains($appartmentPricing)) {
            $this->appartmentPricings[] = $appartmentPricing;
            $appartmentPricing->setIDAppartment($this);
        }

        return $this;
    }

    public function removeAppartmentPricing(AppartmentPricing $appartmentPricing): self
    {
        if ($this->appartmentPricings->removeElement($appartmentPricing)) {
            // set the owning side to null (unless already changed)
            if ($appartmentPricing->getIDAppartment() === $this) {
                $appartmentPricing->setIDAppartment(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    /**
     * @param ArrayCollection $reservations
     */
    public function setReservations(ArrayCollection $reservations): void
    {
        $this->reservations = $reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->addAppartment($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            $reservation->removeAppartment($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->number;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(?string $Location): self
    {
        $this->Location = $Location;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBasePrice(): ?string
    {
        return $this->basePrice;
    }

    public function setBasePrice(string $basePrice): self
    {
        $this->basePrice = $basePrice;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\AppartmentRepository;
use App\Repository\FacilityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/main", name="main")
     * @param FacilityRepository $facilityRepository
     * @return Response
     */
    public function index(FacilityRepository $facilityRepository, AppartmentRepository $appartmentRepository): Response
    {
        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
            'facilities' => $facilityRepository->findAll(),
            'appartments' => $appartmentRepository->findAll()
        ]);
    }
}

templates/main/appartments_section.html.twig
<section id="portfolio" class="portfolio">
    <div class="container">

        <div class="section-title" data-aos="fade-left">
            <h2>
                {% trans %}
                    Appartments
                {% endtrans %}

            </h2>
            <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint
                consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia
                fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>


        <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
            {% for appartment in appartments %}
                <div class="col-lg-4 col-md-6 portfolio-item filter-web">
                    <div class="portfolio-wrap">
                        <img src={{ asset("assets/img/appartments/#{appartment.image}") }} class="img-fluid" alt="">
                        <div class="portfolio-info">
                            <h4>{{ appartment.name }}</h4>
                            <p>{{ appartment.location }}</p>
                            <div class="portfolio-links">
                                <a href={{ asset("assets/img/#{appartment.image}") }} data-gall="portfolioGallery"
                                   class="venobox" title="Web 3">
                                    <i class="bx bx-plus"></i>
                                </a>
                                <a href={{ "/Hotel-Management/public/#{app.request.locale}/appartment/presentation/#{appartment.id}" }}
                                   title="More Details">
                                <i class="bx bx-link">
                                </i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/main/facilities_section.html.twig
<section id="services" class="services section-bg">
    <div class="container">

        <div class="row">
            <div class="col-lg-4">
                <div class="section-title" data-aos="fade-right">
                    <h2> {% trans %}
                        Facilities
                        {% endtrans %}
                    </h2>
                    <p>Cool stuff we offer</p>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="row">
                    {% for facility in facilities %}
                    <div class="col-md-6 d-flex align-items-stretch ">
                        <div class="icon-box" data-aos="zoom-in" data-aos-delay="400">
                            <div class="icon"><i class="bx bx-world"></i></div>
                            <h4><a >{{  facility.name }}</a></h4>
                            <p>{{ facility.Description }}</p>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>

    </div>
</section>